webserver:
  image: telemark/app-tfk-politikere:latest@sha256:67f4a1450dc2d835419e485068de64a841e97a7445760aced61bdc586a447633
  environment:
    SERVER_PORT: 80
    API_URL: http://apiserver_1:3000
  ports:
    - "80:80"
  links:
   - apiserver
apiserver:
  image: telemark/api.t-fk.politikere:latest@sha256:ce2b692e7ab5f86c64f7780fab06f662be68a0b0b82d95bddbdc4193d7dd18ec
  environment:
    SERVER_PORT: 3000
    DB_CONNECTION: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:a7c1784c83536a3c686ec6f0a1c570ad5756b94a1183af88c07df82c5b64663c
  environment:
    DB: tfk
    COLLECTION: politicians
  ports:
   - "27017:27017"
