webserver:
  image: telemark/app-tfk-politikere:latest@sha256:ecde59aa516ea8de1ccaab785537d4c1119014537edca2d19290671dfe42ee9e
  environment:
    SERVER_PORT: 80
    API_URL: http://apiserver_1:3000
  ports:
    - "80:80"
  links:
   - apiserver
apiserver:
  image: telemark/api.t-fk.politikere:latest@sha256:7e37714f28cade3c2423ae50227e0a4b116c8c1f92963a2e329a090e4feab93d
  environment:
    SERVER_PORT: 3000
    DB_CONNECTION: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:69b5754ff6e859b2edb478112d4f091f23c6c0e73d869a80037de3ce587f3dff
  environment:
    DB: tfk
    COLLECTION: politicians
  ports:
   - "27017:27017"
