webserver:
  image: telemark/app-tfk-politikere:latest@sha256:a2ffd944958239a9b6df5343f1081b884e0a0bfbe283fdf01892cbfedfd99b53
  environment:
    SERVER_PORT: 80
    API_URL: http://apiserver_1:3000
  ports:
    - "80:80"
  links:
   - apiserver
apiserver:
  image: telemark/api.t-fk.politikere:latest@sha256:ed0cccbb67f8161fe302e091614ca6a86f7468d27c8d88d05e5840295f384f61
  environment:
    SERVER_PORT: 3000
    DB_CONNECTION: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:630f4cb57049978fa4838b270c19bc365b4827b6f20ee21ee1ab9917587f6d76
  environment:
    DB: tfk
    COLLECTION: politicians
  ports:
   - "27017:27017"
