webserver:
  image: telemark/app-tfk-politikere:latest@sha256:ad668c4f89679f942bcb1f2695b1d2cdcfb3a230a4bc90d86fb89e971e693d5a
  environment:
    SERVER_PORT: 80
    API_URL: http://apiserver_1:3000
  ports:
    - "80:80"
  links:
   - apiserver
apiserver:
  image: telemark/api.t-fk.politikere:latest@sha256:4c040df1a0b278992f88629376194f4fc80e8efccb0240114fde2f7432028c9d
  environment:
    SERVER_PORT: 3000
    DB_CONNECTION: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:3cd83e98091d03d6a7f26a31b75311cf14ff409259d912aaedbc7053504ba105
  environment:
    DB: tfk
    COLLECTION: politicians
  ports:
   - "27017:27017"
